import { makeDefaultLocalBackend } from "./default-backend";
import type { Backend } from "./types";
import { writeStoredBackends } from "./storage";

export const DEMO_LONG_BACKENDS_ENV_FLAG = "VITE_DEMO_LONG_BACKEND_NAMES";

export const DEMO_LONG_BACKEND_IDS = {
  LOCAL_PRIMARY: "demo-long-local-primary",
  LOCAL_STAGING: "demo-long-local-staging",
  CLOUD_PRODUCTION: "demo-long-cloud-production",
  CLOUD_ENTERPRISE: "demo-long-cloud-enterprise",
} as const;

const DEMO_LONG_LOCAL_PRIMARY_NAME =
  "Primary OpenHands Agent Server — West Coast Regional Deployment";
const DEMO_LONG_LOCAL_STAGING_NAME =
  "Staging Environment (Legacy Monorepo Migration Sandbox)";
const DEMO_LONG_CLOUD_PRODUCTION_NAME =
  "Production Cloud — Enterprise Platform Engineering Division";
const DEMO_LONG_CLOUD_ENTERPRISE_NAME =
  "Enterprise Cloud Backend — Customer Success Integrations & Automations";

export function isDemoLongBackendNamesEnabled(): boolean {
  return import.meta.env[DEMO_LONG_BACKENDS_ENV_FLAG] === "true";
}

export function buildDemoLongBackends(
  localHost: string,
  localApiKey: string,
): Backend[] {
  return [
    {
      id: DEMO_LONG_BACKEND_IDS.LOCAL_PRIMARY,
      name: DEMO_LONG_LOCAL_PRIMARY_NAME,
      host: localHost,
      apiKey: localApiKey,
      kind: "local",
    },
    {
      id: DEMO_LONG_BACKEND_IDS.LOCAL_STAGING,
      name: DEMO_LONG_LOCAL_STAGING_NAME,
      host: localHost,
      apiKey: localApiKey,
      kind: "local",
    },
    {
      id: DEMO_LONG_BACKEND_IDS.CLOUD_PRODUCTION,
      name: DEMO_LONG_CLOUD_PRODUCTION_NAME,
      host: "https://app.all-hands.dev",
      apiKey: "demo-long-cloud-production-key",
      kind: "cloud",
    },
    {
      id: DEMO_LONG_BACKEND_IDS.CLOUD_ENTERPRISE,
      name: DEMO_LONG_CLOUD_ENTERPRISE_NAME,
      host: "https://app.all-hands.dev",
      apiKey: "demo-long-cloud-enterprise-key",
      kind: "cloud",
    },
  ];
}

/** Dev-only: append stable demo backends with long labels for dropdown QA. */
export function mergeDemoLongBackends(backends: Backend[]): Backend[] {
  if (!isDemoLongBackendNamesEnabled()) {
    return backends;
  }

  const defaultLocal = makeDefaultLocalBackend();
  const localHost =
    defaultLocal?.host ??
    import.meta.env.VITE_BACKEND_BASE_URL ??
    "http://127.0.0.1:8000";
  const localApiKey = defaultLocal?.apiKey ?? "demo-long-local-key";

  const demos = buildDemoLongBackends(localHost, localApiKey);
  const missing = demos.filter(
    (demo) => !backends.some((backend) => backend.id === demo.id),
  );
  if (missing.length === 0) {
    return backends;
  }

  const merged = [...backends, ...missing];
  writeStoredBackends(merged);
  return merged;
}

/** Mock cloud org fixtures paired with {@link mergeDemoLongBackends}. */
export const DEMO_LONG_CLOUD_ORG_IDS = {
  PERSONAL: "demo-long-org-personal",
  TEAM: "demo-long-org-team",
} as const;

const DEMO_LONG_CLOUD_TEAM_ORG_NAME =
  "Acme Global Platform Engineering — Customer Success & Integrations";

export function getDemoLongCloudOrganizationsResponse() {
  return {
    items: [
      {
        id: DEMO_LONG_CLOUD_ORG_IDS.PERSONAL,
        name: "user_demo_long_org_personal_autogenerated",
        is_personal: true,
      },
      {
        id: DEMO_LONG_CLOUD_ORG_IDS.TEAM,
        name: DEMO_LONG_CLOUD_TEAM_ORG_NAME,
      },
    ],
    current_org_id: DEMO_LONG_CLOUD_ORG_IDS.PERSONAL,
  };
}

export function getDemoLongCloudOrganizationMeResponse(orgId: string) {
  return {
    org_id: orgId,
    user_id: DEMO_LONG_CLOUD_ORG_IDS.PERSONAL,
  };
}

export function getDemoLongCloudCurrentKeyResponse() {
  return {
    id: "demo-long-cloud-key",
    name: "Demo long-name cloud key",
    org_id: DEMO_LONG_CLOUD_ORG_IDS.PERSONAL,
    user_id: DEMO_LONG_CLOUD_ORG_IDS.PERSONAL,
    auth_type: "api_key",
  };
}
