import type { ReactNode } from "react";
import {
  BookOpen,
  Bot,
  Brain,
  Clock,
  Database,
  Flame,
  Folder,
  GitBranch,
  Globe,
  Image as ImageIcon,
  ListTree,
  MousePointerClick,
  Search,
  Sparkles,
  Telescope,
  TestTube,
} from "lucide-react";
import {
  SiAirtable,
  SiAtlassian,
  SiBrave,
  SiClickhouse,
  SiCloudflare,
  SiElevenlabs,
  SiFigma,
  SiGithub,
  SiGitlab,
  SiGooglemaps,
  SiHuggingface,
  SiKagi,
  SiLinear,
  SiMattermost,
  SiMongodb,
  SiNotion,
  SiObsidian,
  SiPaypal,
  SiPostgresql,
  SiPuppeteer,
  SiRedis,
  SiResend,
  SiSentry,
  SiSlack,
  SiSqlite,
  SiStripe,
  SiSupabase,
} from "react-icons/si";
import {
  MCP_CATALOG,
  type MarketplaceField,
  type MarketplaceFieldType,
  type MarketplaceTemplate,
  type McpCatalogEntry,
} from "@openhands/extensions/mcps";

export type { MarketplaceField, MarketplaceFieldType, MarketplaceTemplate };

export interface MarketplaceEntry extends McpCatalogEntry {
  /** Brand-correct logo rendered inside the icon tile. */
  logo: ReactNode;
}

const LOGO = "h-5 w-5";

const MCP_LOGOS: Record<string, ReactNode> = {
  github: <SiGithub className={LOGO} />,
  slack: <SiSlack className={LOGO} />,
  tavily: <Search className={LOGO} strokeWidth={2.5} />,
  linear: <SiLinear className={LOGO} />,
  notion: <SiNotion className={LOGO} />,
  atlassian: <SiAtlassian className={LOGO} />,
  sentry: <SiSentry className={LOGO} />,
  stripe: <SiStripe className={LOGO} />,
  paypal: <SiPaypal className={LOGO} />,
  "cloudflare-docs": <SiCloudflare className={LOGO} />,
  "cloudflare-bindings": <SiCloudflare className={LOGO} />,
  "cloudflare-observability": <SiCloudflare className={LOGO} />,
  huggingface: <SiHuggingface className={LOGO} />,
  deepwiki: <BookOpen className={LOGO} />,
  gitlab: <SiGitlab className={LOGO} />,
  git: <GitBranch className={LOGO} strokeWidth={2.25} />,
  "brave-search": <SiBrave className={LOGO} />,
  exa: <Telescope className={LOGO} strokeWidth={2.25} />,
  firecrawl: <Flame className={LOGO} strokeWidth={2.25} />,
  apify: <Bot className={LOGO} strokeWidth={2.25} />,
  fetch: <Globe className={LOGO} strokeWidth={2.25} />,
  "browser-mcp": <MousePointerClick className={LOGO} strokeWidth={2.25} />,
  playwright: <TestTube className={LOGO} strokeWidth={2.25} />,
  puppeteer: <SiPuppeteer className={LOGO} />,
  "google-maps": <SiGooglemaps className={LOGO} />,
  postgres: <SiPostgresql className={LOGO} />,
  supabase: <SiSupabase className={LOGO} />,
  neon: <Database className={LOGO} strokeWidth={2.25} />,
  mongodb: <SiMongodb className={LOGO} />,
  redis: <SiRedis className={LOGO} />,
  sqlite: <SiSqlite className={LOGO} />,
  filesystem: <Folder className={LOGO} strokeWidth={2.25} />,
  memory: <Brain className={LOGO} strokeWidth={2.25} />,
  "sequential-thinking": <ListTree className={LOGO} strokeWidth={2.25} />,
  time: <Clock className={LOGO} strokeWidth={2.25} />,
  everart: <ImageIcon className={LOGO} strokeWidth={2.25} />,
  everything: <Sparkles className={LOGO} strokeWidth={2.25} />,
  "aws-kb": <BookOpen className={LOGO} strokeWidth={2.25} />,
  figma: <SiFigma className={LOGO} />,
  airtable: <SiAirtable className={LOGO} />,
  obsidian: <SiObsidian className={LOGO} />,
  elevenlabs: <SiElevenlabs className={LOGO} />,
  resend: <SiResend className={LOGO} />,
  "cloudflare-builds": <SiCloudflare className={LOGO} />,
  "cloudflare-browser-rendering": <SiCloudflare className={LOGO} />,
  kagi: <SiKagi className={LOGO} />,
  clickhouse: <SiClickhouse className={LOGO} />,
  mattermost: <SiMattermost className={LOGO} />,
};

export const MCP_MARKETPLACE: MarketplaceEntry[] = MCP_CATALOG.map((entry) => ({
  ...entry,
  logo: MCP_LOGOS[entry.id] ?? <Bot className={LOGO} strokeWidth={2.25} />,
}));
